DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS(
ORDER_ID BIGINT NOT NULL AUTO_INCREMENT,
TABLE_ID BIGINT NOT NULL,
ORDER_STATUS VARCHAR(20) NOT NULL,
PRIMARY KEY (ORDER_ID),
FOREIGN KEY(TABLE_ID) REFERENCES TABLES(TABLE_ID)
);