CREATE TABLE INGREDIENTS(
INGREDIENT_ID BIGINT NOT NULL,
NAME VARCHAR(50) NOT NULL,
EXPIRATION_DATE DATE NOT NULL,
PRIMARY KEY (INGREDIENT_ID)
);

CREATE TABLE MENU_ITEMS(
MENU_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
ITEM_NAME VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL,
PRICE DECIMAL(6,2),
PRIMARY KEY (MENU_ITEM_ID)
);

CREATE TABLE INGREDIENTS_MENU_ITEMS(
MENU_ITEM_ID BIGINT NOT NULL ,
INGREDIENT_ID BIGINT NOT NULL ,
PRIMARY KEY (MENU_ITEM_ID, INGREDIENT_ID),
FOREIGN KEY(INGREDIENT_ID) REFERENCES INGREDIENTS(INGREDIENT_ID),
FOREIGN KEY(MENU_ITEM_ID) REFERENCES MENU_ITEMS(MENU_ITEM_ID)
);

CREATE TABLE ORDERS_MENU_ITEMS(
ORDER_ID BIGINT NOT NULL,
MENU_ITEM_ID BIGINT NOT NULL,
PRIMARY KEY (ORDER_ID, MENU_ITEM_ID),
FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
FOREIGN KEY(MENU_ITEM_ID) REFERENCES MENU_ITEMS(MENU_ITEM_ID)
);

CREATE TABLE ONLINE_ORDERS_MENU_ITEMS(
ORDER_ID BIGINT NOT NULL,
MENU_ITEM_ID BIGINT NOT NULL,
PRIMARY KEY (ORDER_ID, MENU_ITEM_ID),
FOREIGN KEY(ORDER_ID) REFERENCES ONLINE_ORDERS(ORDER_ID),
FOREIGN KEY(MENU_ITEM_ID) REFERENCES MENU_ITEMS(MENU_ITEM_ID)
);
