DROP TABLE IF EXISTS MENU_ITEMS;

CREATE TABLE MENU_ITEMS(
MENU_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
ITEM_NAME VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL,
PRIMARY KEY (MENU_ITEM_ID)
);

DROP TABLE IF EXISTS ORDERS_MENU_ITEMS;

CREATE TABLE ORDERS_MENU_ITEMS(
ORDER_ID BIGINT NOT NULL,
MENU_ITEM_ID BIGINT NOT NULL,
PRIMARY KEY (ORDER_ID, MENU_ITEM_ID),
FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
FOREIGN KEY(MENU_ITEM_ID) REFERENCES MENU_ITEMS(MENU_ITEM_ID)
);

DROP TABLE IF EXISTS ONLINE_ORDERS_MENU_ITEMS;

CREATE TABLE ONLINE_ORDERS_MENU_ITEMS(
ORDER_ID BIGINT NOT NULL,
MENU_ITEM_ID BIGINT NOT NULL,
PRIMARY KEY (ORDER_ID, MENU_ITEM_ID),
FOREIGN KEY(ORDER_ID) REFERENCES ONLINE_ORDERS(ORDER_ID),
FOREIGN KEY(MENU_ITEM_ID) REFERENCES MENU_ITEMS(MENU_ITEM_ID)
);